### ISSUE TITLE
Compiling the basic program throws error about missing mainfont.ttf file

### ISSUE THREAD

**Issue by rishavs** [BlackGoku36/Rice2D#8]
**Describe the bug**
Compiling the basic program throws error about missing mainfont.ttf file

```
Sources/rice2d/App.hx:54: {
    url : C:\Users\risharan\DevSpace\kha\ricer\build\debug-html5\mainfont.ttf, 
    error : Error: ENOENT: no such file or directory, open 'C:\Users\risharan\DevSpace\kha\ricer\build\debug-html5\mainfont.ttf'
}
Log.hx:66
kha/graphics4/PipelineState.hx:111: Warning: Sampler tex not found.
Log.hx:66
The Web Audio autoplay policy will be re-enabled in Chrome 70 (October 2018). Please check that your website is compatible with it. https://goo.gl/7K7WLu
Audio.hx:21
TypeError: Cannot read property 'length' of undefined
    at kha_Assets.loadBlobFromPath.fileName (file:///C:/Users/risharan/DevSpace/kha/ricer/build/debug-html5/kha.js:22724:37)
    at file:///C:/Users/risharan/DevSpace/kha/ricer/build/debug-html5/kha.js:2899:4
    at CallbacksRegistry.apply (C:\Users\risharan\.vscode\extensions\kodetech.electron-debug-18.11.1\.electron\4.0.1\resources\electron.asar\renderer\callbacks-registry.js:47:25)
    at handleMessage (C:\Users\risharan\.vscode\extensions\kodetech.electron-debug-18.11.1\.electron\4.0.1\resources\electron.asar\renderer\api\remote.js:285:21)
    at EventEmitter.ipcRenderer.on.args (C:\Users\risharan\.vscode\extensions\kodetech.electron-debug-18.11.1\.electron\4.0.1\resources\electron.asar\renderer\api\remote.js:275:7)
    at EventEmitter.emit (events.js:182:13)
SystemImpl.hx:59
WebGL: CONTEXT_LOST_WEBGL: loseContext: context lost [file:///C:/Users/risharan/DevSpace/kha/ricer/build/debug-html5/index.html]
```

**To Reproduce**
Use the docs sample for 1st scene. This is the Main.hx;
```
package;

import rice2d.App;

class Main {

    public static function main() {
        new App("scene");// 1
    }
}
```

**Expected behavior**
The app should run without error

**Screenshots**

**Desktop (please complete the following information):**
 - Win10

**Additional context**

**Comment by BlackGoku36** [comment]
There we go: https://github.com/BlackGoku36/Rice2D/commit/3840f520e3eb3f0bf5bc52b92c991587b9327642
It should only ask for main font when using debugger or UI
